# Generated by Django 5.1.4 on 2025-07-16 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_shismemberuser_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='shismemberuser',
            name='fb_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shismemberuser',
            name='ig_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shismemberuser',
            name='note',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='shismemberuser',
            name='x_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
