# Generated by Django 5.1.4 on 2025-07-06 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='events/img')),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('UPCOMING', 'upcoming'), ('DONE', 'done')], default='UPCOMING', max_length=50)),
                ('location', models.CharField(max_length=200)),
                ('time', models.TimeField()),
            ],
        ),
    ]
