# Generated by Django 5.1.4 on 2025-07-12 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_events_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='gallery/img')),
            ],
            options={
                'verbose_name_plural': 'events',
            },
        ),
    ]
