# Generated by Django 5.1.4 on 2025-07-15 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_gallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name_plural': 'galleries'},
        ),
    ]
